version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: twcam1234
      MYSQL_DATABASE: portalAyuntDB
      MYSQL_USER: luongov
      MYSQL_PASSWORD: root1234