apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd
  hostPath:
    path: "/mnt/ssd/mongo"

