version: '3.9'

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    # volumes:
    #   - mongodb_data:/data/fileDB
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: luongov
      MONGO_INITDB_ROOT_PASSWORD: root1234
      MONGO_INITDB_DATABASE: fileDB

# volumes:
#   mongodb_data: